### PR TITLE
fixes for latest mkl release on pip

### LINKED ISSUE #4: not finding mkl on pip
I have noticed that i will not find mkl when installed via `pip install mkl-devel`, I have a virtual environment with that installed and it either tells me it can't find blas or finds another system blas (in this case atlas), which I thought was further down the priority.

### PR DESCRIPTION
**Pull request by jdtuck**
Fixes #4

### CODE REVIEW

**Comment by jdtuck** [comment]
I also noticed all the tabs are standard and not spaces like most formatters like. So I have another commit, reformatting to PEP standards. Look at first commit for the change.

**Comment by david-cortes** [comment]
Thanks for the bug report and PR.

Some of the changes here (function `process_fnames`) would however break the functionality for windows and mac, where the latest MKL names its main file as `mkl_rt.2.dll` and `libmkl_rt.2.dylib` instead of having the number at the end like in linux.

Would you be able to add a modification for this kind of name pattern?

Also weird that it fails like that in linux, since apart from `libmkl_rt.so.2`, there should be a symlink named `libmkl_rt.so` pointing to the earlier file.

**Comment by jdtuck** [comment]
On pip there is no symlink, but I can make that change

**Comment by jdtuck** [comment]
let me know if that works for you

**Comment by david-cortes** [comment]
Thanks, I've pushed some small additional changes - should be working for this new MKL naming on different platforms now.

**Pull request merged**
